apiVersion: v1
kind: Service
metadata:
  name: nutrivision-backend
  labels:
    app: nutrivision
    component: backend
spec:
  selector:
    app: nutrivision
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nutrivision-frontend
  labels:
    app: nutrivision
    component: frontend
spec:
  selector:
    app: nutrivision
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
